### PR TITLE
Dev giacomo

### PR DESCRIPTION
**Pull request by jguterl**

### CODE REVIEW

**Comment by orso82** [comment]
@jguterl @ggdose great to see activity on the ADAS.jl package.

It's odd that GitHub shows 39 files being changed...
image
This makes it hard to understand what has actually changed.

Can you please try to address the merge conflicts and merge master into the `dev_giacomo` branch? This hopefully will clear the differences between `master` and this branch. Thanks!!

**Comment by orso82** [comment]
After talking to @ggdose it sounds like with this commit https://github.com/ProjectTorreyPines/ADAS.jl/commit/2738984b077735b18e0ba79cb9e2e1654ea3d24a `master` is now up to date with this branch. Thank you @jguterl

**Comment by jguterl** [comment]
sorry, I was doing some house cleaning.

**Comment by orso82** [comment]
I ran the regression tests on FUSE and they pass https://github.com/ProjectTorreyPines/FUSE.jl/actions/runs/11961905429. So I'll release a new version of ADAS

**Pull request closed without merging**
